name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'NOTICE'
      - 'PROJECT'
      - 'SECURITY_CONTACTS'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'NOTICE'
      - 'PROJECT'
      - 'SECURITY_CONTACTS'

jobs:
  build-agent:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: build agent
        run: make host-agent-binaries

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: turn off swap
      run: sudo swapoff -a
    
    - name: Set netfilter conntrack max
      run: sudo sysctl -w net.netfilter.nf_conntrack_max=131072

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo@v1.16.5

    - name: Install prequisit packages
      run: sudo apt update && sudo apt install -qq --yes socat ebtables ethtool conntrack

    - name: Run test make target
      run: make test

    - name: Upload test coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: cover.out
        verbose: true
